/**
 * Local archive of finished runs on the DSH machine.
 *
 * Why: the chat card used to stream every video from ComfyUI through the
 * media proxy, so history went blank whenever ComfyUI was offline — and on
 * this setup ComfyUI is offline most of the time (the GPU box flips between
 * video mode and an LLM server). Every run therefore leaves a directory
 * `<archiveDir>/<promptId>/` holding:
 *
 * - `meta.json`, written at SUBMIT time (so a run that finishes while DSH is
 *   restarting is still archivable later): prompt id, the exact API prompt
 *   that was queued, the parameter definitions and the effective values
 *   (randomized seeds included), every seed-like input, status, and — once
 *   archived — the downloaded file list with size and sha256;
 * - the media files, downloaded once on completion via ComfyUI `/view`,
 *   streamed to a `.part` file and renamed into place.
 *
 * Reading is fenced: a prompt id must be a UUID (ComfyUI's own format) and a
 * file name must be listed in that run's meta.json — nothing from a request
 * is ever joined into a path unchecked, and the resolved path must still sit
 * inside the run directory (no symlinks followed out of it).
 */
import { createHash } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { lstat, mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { isAbsolute, join, relative, resolve } from 'node:path';
import { Readable, Transform } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { guessContentType } from './comfyui.js';
/** ComfyUI prompt ids are uuid4 strings; anything else is never a directory name. */
const PROMPT_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
/** Archived file names: generated by us, a conservative charset only. */
const FILE_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,159}$/;
const META = 'meta.json';
export function isPromptId(value) {
    return PROMPT_ID.test(value);
}
/** Seed-like numeric inputs of a prompt (seed, noise_seed, …). */
export function seedsOf(workflow) {
    const seeds = [];
    for (const [nodeId, node] of Object.entries(workflow)) {
        for (const [inputKey, value] of Object.entries(node.inputs ?? {})) {
            if (/seed/i.test(inputKey) && typeof value === 'number')
                seeds.push({ nodeId, classType: node.class_type, inputKey, value });
        }
    }
    return seeds;
}
/** Local file name for one output: `<node>-<index>-<sanitized original>`. */
export function localNameOf(item) {
    const base = (item.filename.split(/[\\/]/).pop() ?? '').replace(/[^A-Za-z0-9._-]/g, '_').replace(/^[._-]+/, '');
    const node = item.node.replace(/[^A-Za-z0-9]/g, '_');
    const name = `${node}-${item.index}-${base === '' ? 'file' : base}`;
    return name.length > 160 ? `${name.slice(0, 120)}${name.slice(-40)}` : name;
}
/** Same-origin URL of an archived file. */
export function archiveUrl(promptId, name) {
    return `/comfyui/archive/${promptId}/${encodeURIComponent(name)}`;
}
function refKey(ref) {
    return `${ref.type ?? 'output'}\u0000${ref.subfolder ?? ''}\u0000${ref.filename}`;
}
/** Whether `child` resolves strictly inside `parent`. */
function inside(parent, child) {
    const rel = relative(parent, child);
    return rel !== '' && !rel.startsWith('..') && !isAbsolute(rel);
}
async function writeJsonAtomic(path, value) {
    const temp = `${path}.${process.pid}.${Date.now()}.tmp`;
    await writeFile(temp, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
    await rename(temp, path);
}
export class RunArchive {
    root;
    inflight = new Map();
    index;
    indexing;
    constructor(root) {
        this.root = root;
    }
    /** The archive root currently in force (absolute). */
    get rootDir() {
        return resolve(this.root());
    }
    /** The run directory, or undefined when the id is not a UUID. */
    dirOf(promptId) {
        return isPromptId(promptId) ? join(this.rootDir, promptId.toLowerCase()) : undefined;
    }
    async readMeta(promptId) {
        const dir = this.dirOf(promptId);
        if (dir === undefined)
            return undefined;
        try {
            const parsed = JSON.parse(await readFile(join(dir, META), 'utf8'));
            return parsed !== null && typeof parsed === 'object' && parsed.promptId !== undefined ? parsed : undefined;
        }
        catch {
            return undefined;
        }
    }
    async writeMeta(meta) {
        const dir = this.dirOf(meta.promptId);
        if (dir === undefined)
            return;
        await mkdir(dir, { recursive: true });
        await writeJsonAtomic(join(dir, META), meta);
    }
    /** Record a run at submit time (status `submitted`, no files yet). */
    async recordSubmission(input) {
        if (!isPromptId(input.promptId))
            return;
        await this.writeMeta({
            version: 1,
            status: 'submitted',
            submittedAt: input.submittedAt ?? new Date().toISOString(),
            ...input,
            seeds: seedsOf(input.workflow),
            files: [],
        });
    }
    /** Mark a run failed / cancelled (keeps whatever was recorded). */
    async markStatus(promptId, status, error) {
        const meta = await this.readMeta(promptId);
        if (meta === undefined || meta.status === 'completed')
            return;
        await this.writeMeta({ ...meta, status, completedAt: new Date().toISOString(), ...(error !== undefined ? { error: error.slice(0, 2000) } : {}) });
    }
    /**
     * Download a finished run's media into its directory (once; concurrent
     * callers share the same work) and mark it completed. Files already on
     * disk with the recorded size are not fetched again.
     */
    archive(opts) {
        const running = this.inflight.get(opts.promptId);
        if (running !== undefined)
            return running;
        const work = this.archiveOnce(opts).finally(() => this.inflight.delete(opts.promptId));
        this.inflight.set(opts.promptId, work);
        return work;
    }
    async archiveOnce(opts) {
        const dir = this.dirOf(opts.promptId);
        if (dir === undefined)
            throw new Error(`prompt id ${opts.promptId} is not a UUID; not archived`);
        await mkdir(dir, { recursive: true });
        const existing = await this.readMeta(opts.promptId);
        const meta = existing ?? {
            version: 1,
            promptId: opts.promptId,
            status: 'submitted',
            submittedAt: new Date().toISOString(),
            workflowName: opts.fallback?.workflowName ?? null,
            source: opts.fallback?.source ?? 'external',
            baseUrl: opts.fallback?.baseUrl ?? '',
            values: opts.fallback?.values ?? {},
            workflow: opts.fallback?.workflow ?? {},
            seeds: seedsOf(opts.fallback?.workflow ?? {}),
            files: [],
        };
        const files = [];
        for (const item of opts.items) {
            const name = localNameOf(item);
            const target = join(dir, name);
            const known = meta.files.find((file) => file.name === name);
            if (known !== undefined) {
                const stat = await lstat(target).catch(() => undefined);
                if (stat !== undefined && stat.isFile() && stat.size === known.bytes) {
                    files.push(known);
                    continue;
                }
            }
            const { bytes, sha256 } = await this.download(item, target, opts.download, opts.maxBytes);
            files.push({ name, filename: item.filename, subfolder: item.subfolder, type: item.type, node: item.node, index: item.index, kind: item.kind, bytes, sha256 });
        }
        const done = { ...meta, status: 'completed', completedAt: new Date().toISOString(), files };
        delete done.error;
        await this.writeMeta(done);
        if (this.index !== undefined && this.index.root === this.rootDir) {
            for (const file of files)
                this.index.refs.set(refKey(file), { promptId: done.promptId, name: file.name });
        }
        return done;
    }
    async download(ref, target, fetchView, maxBytes) {
        const part = `${target}.part`;
        const view = await fetchView(ref);
        if (view.status !== 200 || view.body === null) {
            await view.body?.cancel().catch(() => undefined);
            throw new Error(`下载 ${ref.filename} 失败：ComfyUI /view HTTP ${view.status}`);
        }
        const hash = createHash('sha256');
        let bytes = 0;
        const meter = new Transform({
            transform(chunk, _encoding, callback) {
                bytes += chunk.length;
                if (bytes > maxBytes) {
                    callback(new Error(`${ref.filename} 超过 maxMediaBytes（${maxBytes} 字节），未归档`));
                    return;
                }
                hash.update(chunk);
                callback(null, chunk);
            },
        });
        try {
            await pipeline(Readable.fromWeb(view.body), meter, createWriteStream(part));
            await rename(part, target);
        }
        catch (error) {
            await rm(part, { force: true }).catch(() => undefined);
            throw error;
        }
        return { bytes, sha256: hash.digest('hex') };
    }
    /** Media items rewritten to the local copies (url → archive, proxy kept as fallback). */
    localize(promptId, items, meta) {
        const dir = this.dirOf(promptId);
        return items.map((item) => {
            const file = meta?.files.find((entry) => entry.node === item.node && entry.index === item.index && entry.filename === item.filename);
            if (file === undefined || dir === undefined)
                return { ...item, proxyUrl: item.url };
            return { ...item, url: archiveUrl(promptId, file.name), proxyUrl: item.url, localPath: join(dir, file.name) };
        });
    }
    /** Media items straight from meta.json (no ComfyUI involved). */
    itemsOf(meta, proxyUrl) {
        const dir = this.dirOf(meta.promptId);
        return meta.files.map((file) => ({
            filename: file.filename,
            subfolder: file.subfolder,
            type: file.type,
            node: file.node,
            index: file.index,
            kind: file.kind,
            url: archiveUrl(meta.promptId, file.name),
            proxyUrl: proxyUrl(file),
            ...(dir !== undefined ? { localPath: join(dir, file.name) } : {}),
        }));
    }
    /**
     * Resolve one archived file for serving. Undefined unless the id is a UUID,
     * the name is one this run's meta.json lists, and the path is a regular
     * file (not a symlink) strictly inside the run directory.
     */
    async resolveFile(promptId, name) {
        const dir = this.dirOf(promptId);
        if (dir === undefined || !FILE_NAME.test(name))
            return undefined;
        const meta = await this.readMeta(promptId);
        const file = meta?.files.find((entry) => entry.name === name);
        if (file === undefined)
            return undefined;
        const path = resolve(dir, name);
        if (!inside(dir, path))
            return undefined;
        const stat = await lstat(path).catch(() => undefined);
        if (stat === undefined || !stat.isFile())
            return undefined;
        return { path, size: stat.size, file };
    }
    /** The archived copy of a ComfyUI file reference, if any run downloaded it. */
    async findByRef(ref) {
        await this.ensureIndex();
        return this.index?.refs.get(refKey(ref));
    }
    async ensureIndex() {
        const root = this.rootDir;
        if (this.index?.root === root)
            return;
        if (this.indexing !== undefined)
            return this.indexing;
        this.indexing = (async () => {
            const refs = new Map();
            const entries = await readdir(root, { withFileTypes: true }).catch(() => []);
            for (const entry of entries) {
                if (!entry.isDirectory() || !isPromptId(entry.name))
                    continue;
                const meta = await this.readMeta(entry.name);
                for (const file of meta?.files ?? [])
                    refs.set(refKey(file), { promptId: entry.name, name: file.name });
            }
            this.index = { root, refs };
        })().finally(() => { this.indexing = undefined; });
        return this.indexing;
    }
}
/**
 * Serve one local file with single-range support (206 / 416 / HEAD), so the
 * <video> element can seek: without Range the seekable range stays empty and
 * the progress bar snaps back.
 */
export async function serveLocalFile(request, response, file) {
    const head = {
        'content-type': file.contentType ?? guessContentType(file.path),
        'accept-ranges': 'bytes',
        'cache-control': 'private, max-age=86400',
        'x-content-type-options': 'nosniff',
    };
    const range = parseRange(request.headers.range, file.size);
    if (range === 'unsatisfiable') {
        response.writeHead(416, { ...head, 'content-range': `bytes */${file.size}` });
        response.end();
        return;
    }
    const start = range?.start ?? 0;
    const end = range?.end ?? file.size - 1;
    const status = range === undefined ? 200 : 206;
    response.writeHead(status, {
        ...head,
        'content-length': file.size === 0 ? 0 : end - start + 1,
        ...(range !== undefined ? { 'content-range': `bytes ${start}-${end}/${file.size}` } : {}),
    });
    if (request.method === 'HEAD' || file.size === 0) {
        response.end();
        return;
    }
    await pipeline(createReadStream(file.path, { start, end }), response);
}
/** Parse a single `bytes=` range; undefined = whole file. Multi-range requests get the whole file. */
export function parseRange(header, size) {
    if (header === undefined)
        return undefined;
    const match = /^bytes=(\d*)-(\d*)$/.exec(header.trim());
    if (match === null)
        return undefined;
    const [, first = '', last = ''] = match;
    if (first === '' && last === '')
        return undefined;
    if (first === '') {
        const suffix = Number(last);
        if (suffix === 0)
            return 'unsatisfiable';
        return { start: Math.max(0, size - suffix), end: size - 1 };
    }
    const start = Number(first);
    if (start >= size)
        return 'unsatisfiable';
    const end = last === '' ? size - 1 : Math.min(Number(last), size - 1);
    if (end < start)
        return 'unsatisfiable';
    return { start, end };
}
